game/routes.py
import logging
import flask

from firebase_interface import _send_firebase_message, create_custom_token
from gaesessions import get_current_session
from game.model import GameState, TileEntity
import urllib

import build_ids

from flask import request

r_game = flask.Blueprint('game', __name__, template_folder='templates')

# game_id = 1
# player_id = 1


def create_game_session():
    """
    Creates or retrieves the counter and sets the session state
    :return:
    returns template values that can be passed to the render_template
    method
    """
    global game_id
    logging.info("Create a new session for a game")

    # Check if a session already exists, create it if it doesn't
    session = get_current_session()
    user = session.get("id", 0)
    if user == 0:
        session["id"] = str(build_ids.new_user_id())
        user = session["id"]

    # user = users.get_current_user()

    key = request.args.get('g')

    if not key:
        # Create a new game
        key = session["id"]

        # ships = [
        #     TileEntity(type=user, row=0, col=0)
        # ]

        my_game = GameState(id=key, tiles=[], users=[user])
        my_game.put()
    else:
        my_game = GameState.get_by_id(key)
        if not my_game:
            return 'No Such Game', 404
        if user not in my_game.users:
            my_game.users.append(user)
            # my_game.add_user(user)
            my_game.put()

    channel_id = user + key

    # [START pass_token]
    client_auth_token = create_custom_token(channel_id)
    _send_firebase_message(channel_id, message=my_game.to_json())

    game_link = '{}?g={}'.format(request.base_url, key)

    template_values = {
        'token': client_auth_token,
        'channel_id': channel_id,
        'me': user,
        'game_key': key,
        'game_link': game_link,
        'initial_message': urllib.unquote(my_game.to_json())
    }
    # [END pass_token]

    return template_values


@r_game.route("/game")
def start_game():
    logging.info("Main Game start")
    template_values = create_game_session()
    return flask.render_template("game_index2.html", **template_values)


@r_game.route("/game/open", methods=['POST'])
def open_game():
    """
    Send a message to acknowledge a listener
    :return:
    """
    logging.info("Opening Game Channel")
    logging.info(request)
    game = GameState.get_by_id(request.args.get('g'))
    if not game:
        return 'Game not found', 404
    game.send_update("open")
    return ''


@r_game.route("/game/join", methods=['POST'])
def join_game():
    """
    Called when a new user wants to join an
    existing game
    :return:
    """
    logging.info("Joining Game")
    game = GameState.get_by_id(request.args.get('g'))
    if not game:
        return 'Game not found', 404

    # Get session ID
    """
    A LOT OF THIS SHOULD BE SPLIT TO A DEDICATED
    LOBBY ROUTINE
    """
    session = get_current_session()
    user = session.get("id", 0)
    if user == 0:
        session["id"] = str(build_ids.new_user_id())
        user = session["id"]
    else:
        build_ids.update_user_id()

    if user in game.list_users():
        logging.info("User already present")
        game.notify_user_position(user)
        return ''

    # Create a position and stick the user in
    pos = game.random_empty_position()
    game.add_user(session["id"], pos[0], pos[1])
    logging.info("Attempting join")
    return ''


@r_game.route("/game/move", methods=['POST'])
def game_move():
    """
    Handle the moving logic from the game
    :return:
    """
    logging.info(request.form.get('x'))
    my_id = request.form.get('id')
    col = request.form.get('x')
    row = request.form.get('y')
    logging.info("Row: " + str(row))
    logging.info("Col: " + str(col))
    game = GameState.get_by_id(request.args.get('g'))
    game.move(my_id, row, col)
    return ''

server/solo/routes.py
import os
from flask import Blueprint, render_template, request, redirect, url_for
from ..gaesessions import get_current_session
import random

solo = Blueprint('solo', __name__, template_folder=os.path.abspath('templates'))


def create_id():
    """
    Create a random-ish user ID
    :return:
    """
    uid = str(random.randint(1, 1000))
    uname = "Player" + str(uid)

    return uid, uname


@solo.route("/")
def start():
    """
    Extract the information from the user session
    Allow the user to change their username
    :return:
    """
    session = get_current_session()

    uid = session.get("id", "0")
    uname = session.get("name", "")

    if uid == "0" or uname == "":
        (uid, uname) = create_id()
        session["id"] = uid
        session["name"] = uname
        assert session["id"] != "0", "Bad id!"
        assert session["name"] != "", "Bad name!"

    template_values = {
        'uid': uid,
        'uname': uname
    }

    return render_template('entry.html', **template_values)


@solo.route('/change-name', methods=['POST'])
def set_username():
    session = get_current_session()
    session["name"] = request.form['name']

    return redirect(url_for('solo.start'))


@solo.route('/solo-join-game', methods=['POST'])
def solo_join_game():
    return redirect(url_for('game.start_game'), code=307)

templates/_firebase_config.html
<script src="https://www.gstatic.com/firebasejs/5.5.9/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyABYPdWIF56Ff7HbPQ-nJfE9YY0Fcc_eeQ",
    authDomain: "fir-test-222916.firebaseapp.com",
    databaseURL: "https://fir-test-222916.firebaseio.com",
    projectId: "firebase-test-222916",
    storageBucket: "firebase-test-222916.appspot.com",
    messagingSenderId: "368557792160"
  };
  firebase.initializeApp(config);
</script>

templates/count_intex.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    {% include "_firebase_config.html" %}
    <link rel="stylesheet" type="text/css" href="static/main.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="static/count.js"></script>
    <script>
      initGame('{{ game_key }}', '{{ me }}', '{{ token }}', '{{ channel_id }}',
          {# use the |safe flag to get unescaped json to render #}
          {{ initial_message|safe }});
    </script>
  </head>
  <body>
    <div id="display-area" class="waiting">
      <h2>Firebase-enabled Tic Tac Toe</h2>
      <div id="other-player">
        Waiting for another player to join.<br>
        Send them this link to play:<br>
        <div id="game-link"><a href="{{ game_link }}">{{ game_link }}</a></div>
      </div>
      <div id="number"></div>
      <div id="board">
        <div class="t l cell" id="0"></div>  
      </div>
      <div id="this-game" float="top">
        Quick link to this game: <span id="this-game-link"><a href="{{ game_link }}">{{ game_link }}</a></span>
      </div>
    </div>
  </body>
</html>

templates/entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ironclad</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="static/entry.css" />
</head>
<body>
    <h1>Ironclad TypeTester</h1>
    <div id="user-details">
        <h2>User Details:</h2>
        <h3>User ID: {{ uid }} </h3>
        <h3>Currently Set Username: {{ uname }} </h3>

        <form method="post" action="{{ url_for('solo.set_username') }}">
            <label form="name" class="form label">Name:</label>
            <input type="text" name="name" value="{{ uname }}" class="form text-box">
            <input type="submit" value="Change Username" id="change-button">
        </form>
    </div>
    <div id="game-details">
        <h2>Start/Join Game:</h2>
        <a href="{{ url_for('game.start_game') }}"><button id="start-button">Start New Lobby</button></a>
        <form method="post" action="{{ url_for('solo.solo_join_game') }}">
            <label form="pin" class="form label">PIN:</label>
            <input type="text" name="pin" value="" class="form text-box">
            <input type="submit" value="Join Lobby" id="join-button">
        </form>

    </div>
</body>
</html>

templates/game_index2.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Ironclad Game</title>
         <!-- {% include "_firebase_config.html" %}  -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> -->

    </head>
    <link rel="stylesheet" type="text/css" href="static/main.css" />
    <!-- <script src="static/lib/pixi.min.js"></script>  -->
    <!-- import javascript game files here -->
    <body>
    <h1>Ironclad TypeTester <span id="h1lobby">Lobby</span></h1>
        <div id="pin">
            <h2>Your friends will need this PIN code to join the lobby: {{ game_key }}</h2>
        </div>
        <div id="game-over"></div>
        <div id="userList">
            <h3>Users in Lobby:</h3>
            <hr />
            <div id="users"></div>
            {%  if host %}
                <button id="start-game">Start!</button>
            {% endif %}
        </div>
        <div id="accuracyTracker">
            <h3>Type the text in the black box!</h3>
            <p id="AClog"></p>
        </div>
        <div id="gameboard"></div>

        <!-- <script src="static/lib/classes/grid.js"></script>
        <script src="static/lib/classes/ocean.js"></script>
        <script src="static/lib/classes/ship.js"></script>
        <script src="static/lib/classes/newShip.js"></script>
        <script src="static/lib/classes/utility.js"></script>
        <script src="static/lib/classes/keyboard.js"></script>
        <script src="static/lib/classes/missileController.js"></script>
        <script src="static/lib/classes/highlightedSquare.js"></script>
        <script src="static/lib/classes/sound.js"></script>
        <script src="static/lib/classes/buttonManager.js"></script>
        <script src="static/lib/classes/lowerConsole.js"></script>
        <script src="static/lib/classes/test.js"></script>
        <script src="static/lib/classes/enemyTracker.js"></script>
        <script src="static/lib/classes/enemy.js"></script>
        <script src="static/Game.js"></script> -->
        <script src="static/bundle.js"></script> <!-- Uncomment this and next script tag -->
        <script>
          Battleships.initGame('{{ game_key }}', '{{ me }}', '{{ token }}', '{{ channel_id }}',
              {# use the |safe flag to get unescaped json to render #}
              {{ initial_message|safe }});
        </script>
        <!-- <script>
            initGame('{{ game_key }}', '{{ me }}', '{{ token }}', '{{ channel_id }}',
                {# use the |safe flag to get unescaped json to render #}
                {{ initial_message|safe }});
          </script> -->
    </body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>How should this work?</title>
    <!-- Firebase App is always required and must be first -->
    <script src="https://www.gstatic.com/firebasejs/5.5.9/firebase-app.js"></script>

    <script src="https://www.gstatic.com/firebasejs/5.5.9/firebase.js"></script>
    <script>
      // Initialize Firebase
      var config = {
        apiKey: "AIzaSyABYPdWIF56Ff7HbPQ-nJfE9YY0Fcc_eeQ",
        authDomain: "fir-test-222916.firebaseapp.com",
        databaseURL: "https://fir-test-222916.firebaseio.com",
        projectId: "firebase-test-222916",
        storageBucket: "firebase-test-222916.appspot.com",
        messagingSenderId: "368557792160"
      };
      firebase.initializeApp(config);
    </script>
</head>
<body>

</body>
</html>